#!bin/bash


#exporting python and dsbulk
export PATH=/dsbulk-1.8.0/bin:$PATH
export PYTHONIOENCODING=utf-8

tar_file=$1
user_auth=$2
pass_auth=$3
bkp_name=$4





keyspace=$(basename "${tar_file}" ".tar.gz")

tar -xvzf "${tar_file}"

echo "adding request timeout"
cqlsh -u $user_auth -p $pass_auth -e --request-timeout=6000
echo "Drop keyspace ${keyspace}"
cqlsh -u $user_auth -p $pass_auth -e "drop keyspace \"${keyspace}\";"


echo "Create empty keyspace: ${keyspace}"
cat "${bkp_name}/${keyspace}.sql" | cqlsh -u $user_auth -p $pass_auth



for dir in "${bkp_name}/"*/;
do
 str=$dir
 str2=$(echo $str | sed 's|^[^/]*\(/[^/]*/\).*$|\1|')
 table_n=$(echo $str2 | sed 's/^\///;s/\// /g')
 table_n2=${table_n::-5}
 #file_path=${dir}output-000001.csv
 FILES=${dir}*

 for f in $FILES
 do
 dsbulk load -u $user_auth -p $pass_auth -url $f -k $keyspace -t $table_n2 --dsbulk.connector.csv.maxCharsPerColumn 900000 -header true -logDir /tmp/logs
 done

done
